cc  -g -fno-inline -Wall -o sort_SWIFT.exe sort_SWIFT.c
cc  -g -fno-inline -Wall -o sort_RXTE.exe sort_RXTE.c
cc  -g -fno-inline -Wall -o sort_Chan_XMM_Suz_Int.exe sort_Chan_XMM_Suz_Int.c
gfortran -o track.exe track.f
gfortran -o masterephem.exe masterephem.f
